### Decision Tree Algorithm

Decision Tree is a supervised machine learning algorithm that can be used for both classification and regression tasks. It works by recursively splitting the data into subsets based on the feature that provides the best separation of the target variable. The resulting tree structure consists of nodes representing features, branches representing decision rules, and leaf nodes representing the predicted outcomes.

- Elements of a Decision Tree:
  - Root Node: The topmost node that represents the entire dataset. The data divides from this node based on the feature that provides the best split.
  - Decision Nodes: Nodes that represent features used for splitting the data. Each decision node splits into further nodes.
  - Internal Nodes: Nodes that are not leaf nodes, which represent the features used for splitting.
  - Leaf/Terminal Nodes: Nodes that represent the predicted outcome or class label.
  - Splitting: The process of dividing the dataset into subsets based on feature values.
  - Pruning: The process of removing branches from the tree to prevent overfitting and improve generalization.
  - Branch: A connection between nodes that represents a decision rule based on feature values.

##### Entropy, Gini Impurity and Information Gain Theory

- Impurity measures how mixed the classes are in a node. A node is pure if all samples belong to the same class.
  - Highest impurity is when the classes are perfectly mixed, e.g the root node of the tree, and the lowest impurity is when all samples belong to the same class, e.g a leaf node of the tree.
  - When we split a node, we split the impurity of the parent node into the child nodes. The goal is to reduce the impurity as much as possible with each split.
  - We either measure Entropy, Gini Impurity or Information Gain to determine the best split for a node.
  - Impurity is also called "disorder" or "uncertainty". The higher the entropy, the more mixed the classes are in the node. The lower the entropy, the more pure the node is.

##### Entropy:
- Measure of randomness/disorder or impurity in the data. It is calculated as:
  - Entropy(S) = -p1*log2(p1) - p2*log2(p2) - ... - pk*log2(pk) OR Entropy(S) = -Σ(pi*log2(pi)) for i=1 to k
  - Where p1, p2, ..., pk are the proportions of each class in the node.
  - A node with only one class has an entropy of 0 (pure), while a node with a 50-50 split has an entropy of 1 (most impure).
- It is used to quantify the impurity of a node and to determine the best feature for splitting the data.
- Entropy is 0 when all samples belong to the same class (pure node) and is 1 when the classes are perfectly mixed (most impure node).

#### Information Gain:
- Information Gain is the reduction in entropy after a dataset is split on an attribute. It is calculated as:
  - Information Gain(S, A) = Entropy(S) - Weighted Average Entropy of the subsets created by splitting on attribute A
  - The attribute with the highest information gain is chosen for the split.
- Information Gain is maximized when the split results in pure subsets (i.e., subsets with low entropy). Leaf Node is pure when it contains samples of only one class, which means the entropy is 0. Therefore, a split that results in pure subsets will have a high information gain, as it significantly reduces the entropy from the parent node to the child nodes.
- It is used in Decision Trees to decide the ordering of attributes at each node.
- A higher Information Gain implies a better split, as it indicates a greater reduction in impurity.

#### Gini Impurity:
- Gini Impurity is another measure used to determine how often a randomly chosen element from the set would be incorrectly labeled if it was randomly labeled according to the distribution of labels in the subset. It is calculated as:
  - Gini(S) = 1 - Σ(pi^2) for i=1 to k
  - Where pi is the proportion of samples belonging to class i in the node.
- Gini impurity is 0 if all elements belong to a single class (pure node) and is at its maximum when the classes are perfectly mixed (most impure node).

- Entropy vs Gini Impurity
    - Both are measures of impurity used in decision trees to determine the best split. Used interchangeably.
    - The choice between them can depend on the specific dataset and the problem at hand. 
    - In practice, Gini impurity is often preferred for classification tasks due to its computational efficiency, while entropy can be more informative in certain cases where the distribution of classes is more complex.

- These 3 measures help in building decision trees by determining the best splits at each node to maximize the purity of the resulting subsets, which in turn leads to better predictions.

In [94]:
import math

In [95]:
# Example Dataset
# Let's say we have a dataset with two classes, A and B
# Suppose in a dataset of 10 elements, 4 are of class A and 6 are of class B.

# Number of elements in each class

n_A = 4
n_B = 6

# Total number of elements
n_total = n_A + n_B

In [96]:
# Calculate the proportion of each class
p_A = n_A / n_total
p_B = n_B / n_total

# Calculate Entropy
entropy = - (p_A * math.log2(p_A) + p_B * math.log2(p_B))

# Print
print(f"Proportion of class A: {p_A:.2f}")
print(f"Proportion of class B: {p_B:.2f}")
print(f"Entropy of the dataset: {entropy:.4f}")

Proportion of class A: 0.40
Proportion of class B: 0.60
Entropy of the dataset: 0.9710

In [97]:
# Calculate Gini Impurity

gini = 1 - p_A**2 - p_B**2
print(f"Gini Impurity of the dataset: {gini:.4f}")

Gini Impurity of the dataset: 0.4800

In [98]:
# Calculate Information Gain

# Let's say we split the dataset based on a feature that results in two subsets:
# Subset 1: 2 elements of class A and 3 elements of class B
# Subset 2: 2 elements of class A and 3 elements of class B

# n_1_A, n_1_B = 2, 3
# n_2_A, n_2_B = 2, 3
n_1_A, n_1_B = 1, 3
n_2_A, n_2_B = 3, 3


p_1_A = n_1_A / (n_1_A + n_1_B)
p_1_B = n_1_B / (n_1_A + n_1_B)
entropy_1 = - (p_1_A * math.log2(p_1_A) + p_1_B * math.log2(p_1_B)) 

p_2_A = n_2_A / (n_2_A + n_2_B)
p_2_B = n_2_B / (n_2_A + n_2_B)
entropy_2 = - (p_2_A * math.log2(p_2_A) + p_2_B * math.log2(p_2_B))


# Calculating Information Gain
info_gain = entropy - ( (n_1_A + n_1_B) / n_total * entropy_1 + (n_2_A + n_2_B) / n_total * entropy_2 )
print(f"Information Gain from the split: {info_gain:.4f}")

Information Gain from the split: 0.0464

In [99]:
# We got an Information Gain of 0.0000, which means that the split did not reduce the entropy of the dataset, and thus it is not a good split.

In [100]:
# We then got Information Gain of 0.0464

## Decision Tree Example

In [101]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

In [102]:
# Import titanic dataset
df = sns.load_dataset('titanic')

In [103]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [104]:
# Drop deck
df.drop('deck', axis=1, inplace=True)

# Imput missing values of age and fare with median
imputer = SimpleImputer(strategy='median')
df[['age', 'fare']] = imputer.fit_transform(df[['age', 'fare']])

In [105]:
# Impute missing values of embarked and embark_town
embark_imputer = SimpleImputer(strategy='most_frequent')
df[['embarked', 'embark_town']] = embark_imputer.fit_transform(df[['embarked', 'embark_town']])

In [106]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [107]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [108]:
sex_encoder = LabelEncoder()
df['sex'] = sex_encoder.fit_transform(df['sex'])

In [109]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,0,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,0,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,0,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,1,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

In [110]:
# Encode the rest of the categorical and object variables
le = LabelEncoder()

for col in df.select_dtypes(include=['category', 'object']):
    df[col] = le.fit_transform(df[col])

C:\Users\mypci\AppData\Local\Temp\ipykernel_6356\4201465874.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=['category', 'object']):

In [111]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

In [112]:
# Split X and y
# X = df.drop('survived', axis=1)
X = df.drop(['survived', 'alive'], axis=1)
y = df['survived']

In [113]:
# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [114]:
# Create and train the model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

In [115]:
# Evaluate the model

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[100  15]
 [ 21  43]]
              precision    recall  f1-score   support

           0       0.83      0.87      0.85       115
           1       0.74      0.67      0.70        64

    accuracy                           0.80       179
   macro avg       0.78      0.77      0.78       179
weighted avg       0.80      0.80      0.80       179

In [116]:
# Save the decision tree
from sklearn.tree import export_graphviz
export_graphviz(model, out_file='./savedModels/05_DecisionTree03.dot', feature_names=X.columns, filled=True, rounded=True)